GYMONE/GYMONE/GYMONE/Controllers/DetailsReportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CrystalDecisions.CrystalReports.Engine;
using GYMONE.Filters;
using GYMONE.Repository;

namespace GYMONE.Controllers
{
    [MyExceptionHandler]
    [Authorize(Roles = "SystemUser,Admin")]
    public class DetailsReportController : Controller
    {
        IlReports objIlReports;

        public DetailsReportController()
        {
            objIlReports = new ReportsMaster();
        }

        [HttpGet]
        public ActionResult DetailsMemberReport()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DetailsMemberReport(FormCollection fc)
        {
            DataSet ds = objIlReports.Generate_AllMemberDetailsReport();
            ds.Tables[0].TableName = "DtMember";

            if (ds.Tables[0].Rows.Count > 0)
            {
                ReportClass rptH = new ReportClass();
                rptH.FileName = Server.MapPath("~/Reports/AllMemberDetailsReport.rpt");
                rptH.Load();
                rptH.SetDataSource(ds.Tables[0]);
                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();

                Stream stream = rptH.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                stream.Seek(0, SeekOrigin.Begin);
                return File(stream, "application/pdf", "DetailsReport.pdf");
            }

            return View();
        }


    }
}

GYMONE/GYMONE/GYMONE/Views/DetailsReport/DetailsMemberReport.cshtml
@{
    ViewBag.Title = "DetailsMemberReport";
}

<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<script src="~/bootstrap/js/bootstrap.min.js"></script>
<link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />


<div class="container">
    <div style="margin-top: 10px"></div>
    <fieldset>

        <legend class="legend">All Member Report Download</legend>

        <div class="panel">

            <div class="panel-body">

                @using (Html.BeginForm("DetailsMemberReport", "DetailsReport", FormMethod.Post))
                {
                     @Html.AntiForgeryToken()
                    <div style="margin-top: 5px"></div>
                    <div class="row">
                        <div class="col-md-6">
                            All Member Report According to Renwal Date :- 
                        </div>
                        <div class="col-md-6">
                            <input id="submitval" class="btn btn-success" type="submit" name="actionType" value="Download" />
                        </div>
                    </div>
                    <div style="margin-top: 5px"></div>
                }
            </div>

        </div>
    </fieldset>
</div>